# DCT Basics

In [1]:
# Import functions and libraries
import numpy as np
import matplotlib.pyplot as plt

import numpy as np
import scipy as sc
import scipy.fft as fft

%matplotlib inline
plt.rcParams['figure.figsize'] = (20.0, 7.0)

In [2]:
x = [1.5, 0.8, -0.7, 0.4]

Looking at scipy documentation (https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.dct.html), we see that the DCT $y_k$ of a signal $x_n$ is defined as

$$
y_k = 2 \sum_{n=0}^{N-1} x_n \cos\left(\frac{\pi k(2n+1)}{2N} \right)
$$

In [5]:
dct_x = fft.dct(x)
dct_x

array([ 4.        ,  3.18058527,  2.54558441, -1.92973505])

As $y_0 = 2 \sum_n x_n$, we have

In [7]:
np.sum(x)

2.0

Taking the inverse transform yields the original signal.

In [8]:
fft.idct(dct_x)

array([ 1.5,  0.8, -0.7,  0.4])

By a clever arrangement of the signal, the DCT can be calculated by means of FFT. We make the signal 4 times longer and add a zero at even indices. In the second part of the signal, we put the original signal in reverse.

Then we take the FFT.

In [12]:
xbig = [0, 1.5, 0, 0.8, 0, -0.7, 0, 0.4, 0, 0.4, 0, -0.7, 0, 0.8, 0, 1.5]
fft.fft(xbig)

array([ 4.        -0.j,  3.18058527+0.j,  2.54558441-0.j, -1.92973505+0.j,
        0.        +0.j,  1.92973505+0.j, -2.54558441+0.j, -3.18058527+0.j,
       -4.        -0.j, -3.18058527-0.j, -2.54558441-0.j,  1.92973505-0.j,
        0.        -0.j, -1.92973505-0.j,  2.54558441+0.j,  3.18058527-0.j])