In [1]:
import torch
import torch.nn as nn

# Max Pool 1D

In [12]:
x = torch.randn(1,8)
x

tensor([[ 0.8992, -0.4114, -0.4742,  0.2282,  0.2838, -3.1396, -1.9118, -0.8298]])

In [13]:
m = nn.MaxPool1d(2)
m(x)

tensor([[ 0.8992,  0.2282,  0.2838, -0.8298]])

In [14]:
m = nn.MaxPool1d(4)
m(x)

tensor([[0.8992, 0.2838]])

In [15]:
m = nn.MaxPool1d(3, stride = 2)
m(x)

tensor([[0.8992, 0.2838, 0.2838]])

# Max Pool 2D

In [22]:
x = torch.randn(1,6,6)
x

tensor([[[-0.5882, -0.1216,  1.0357, -1.1981,  1.4594,  1.8051],
         [ 0.2442,  0.0792, -1.2018, -0.4652, -0.2550, -0.7989],
         [-1.1653, -0.7500, -1.5597, -0.7099, -1.0480,  0.9462],
         [-2.0504, -1.4228,  0.1169, -1.9314, -0.0355, -0.2100],
         [-0.9117, -0.5223,  1.3240, -0.2241,  0.4574, -1.3613],
         [-0.4340,  0.0498,  1.1892,  0.1217, -0.0615,  0.7308]]])

In [23]:
m = nn.MaxPool2d(3)
m(x)

tensor([[[1.0357, 1.8051],
         [1.3240, 0.7308]]])