In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

# Avg Pool 1D

In [2]:
x = torch.randn(1,8)
x

tensor([[ 1.2289,  0.1982, -0.4322,  1.4118, -2.1716, -0.0349, -0.9194,  0.6924]])

In [4]:
layer = nn.AvgPool1d(2)
layer(x)

tensor([[ 0.7135,  0.4898, -1.1032, -0.1135]])

In [9]:
((x[0,0] + x[0,1])/2, (x[0,2] + x[0,3])/2, (x[0,4] + x[0,5])/2, (x[0,6] + x[0,7])/2)

(tensor(0.7135), tensor(0.4898), tensor(-1.1032), tensor(-0.1135))

In [11]:
layer = nn.AvgPool1d(2, 3)
layer(x)

tensor([[ 0.7135, -0.3799, -0.1135]])

In [17]:
((x[0,0] + x[0,1])/2, (x[0,3] + x[0,4])/2, (x[0,6] + x[0,7])/2)

(tensor(0.7135), tensor(-0.3799), tensor(-0.1135))